/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application;

import controllers.FacturaJpaController;
import controllers.exceptions.NonexistentEntityException;
import entities.Factura;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ERICK
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        // labels y buttons invisibles hasta que se ejecute su respectivo button
        create_c.setVisible(false);
        create_f.setVisible(false);
        create_d.setVisible(false);
        create_t.setVisible(false);
        
        create_cr.setVisible(false);
        create_fr.setVisible(false);
        create_dr.setVisible(false);
        create_tr.setVisible(false);
        
        create_right.setVisible(false);
        create_wrong.setVisible(false);
        
        create_ejecutar.setVisible(false);
        comprobar.setVisible(false);
        comprobar_error.setVisible(false);
        update_ejecutar.setVisible(false);
        delete_ejecutar.setVisible(false);
        
        Factura nuevaFactura = new Factura();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        create = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        read = new javax.swing.JButton();
        create_cr = new javax.swing.JTextField();
        create_c = new javax.swing.JLabel();
        create_f = new javax.swing.JLabel();
        create_d = new javax.swing.JLabel();
        create_t = new javax.swing.JLabel();
        create_fr = new javax.swing.JTextField();
        create_dr = new javax.swing.JTextField();
        create_tr = new javax.swing.JTextField();
        create_ejecutar = new javax.swing.JButton();
        create_right = new javax.swing.JLabel();
        create_wrong = new javax.swing.JLabel();
        comprobar = new javax.swing.JButton();
        comprobar_error = new javax.swing.JLabel();
        update_ejecutar = new javax.swing.JButton();
        delete_ejecutar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        create.setBackground(new java.awt.Color(0, 0, 0));
        create.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        create.setForeground(new java.awt.Color(255, 255, 255));
        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        read.setBackground(new java.awt.Color(0, 0, 0));
        read.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        read.setForeground(new java.awt.Color(255, 255, 255));
        read.setText("Read");
        read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readActionPerformed(evt);
            }
        });

        create_cr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_crActionPerformed(evt);
            }
        });

        create_c.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        create_c.setForeground(new java.awt.Color(255, 255, 255));
        create_c.setText("Código");

        create_f.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        create_f.setForeground(new java.awt.Color(255, 255, 255));
        create_f.setText("Fecha");

        create_d.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        create_d.setForeground(new java.awt.Color(255, 255, 255));
        create_d.setText("Descripción");

        create_t.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        create_t.setForeground(new java.awt.Color(255, 255, 255));
        create_t.setText("Total importe");

        create_ejecutar.setBackground(new java.awt.Color(0, 0, 0));
        create_ejecutar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        create_ejecutar.setForeground(new java.awt.Color(255, 255, 255));
        create_ejecutar.setText("Ejecutar");
        create_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_ejecutarActionPerformed(evt);
            }
        });

        create_right.setForeground(new java.awt.Color(0, 102, 0));
        create_right.setText("¡Los datos han sido añadidos correctamente!");

        create_wrong.setForeground(new java.awt.Color(204, 0, 51));
        create_wrong.setText("¡Error al añadir los datos!");

        comprobar.setBackground(new java.awt.Color(0, 0, 0));
        comprobar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comprobar.setForeground(new java.awt.Color(255, 255, 255));
        comprobar.setText("Comprobar");
        comprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprobarActionPerformed(evt);
            }
        });

        comprobar_error.setForeground(new java.awt.Color(204, 0, 0));
        comprobar_error.setText("¡Los datos no han sido encontrados!");

        update_ejecutar.setBackground(new java.awt.Color(0, 0, 0));
        update_ejecutar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update_ejecutar.setForeground(new java.awt.Color(255, 255, 255));
        update_ejecutar.setText("Actualizar");
        update_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_ejecutarActionPerformed(evt);
            }
        });

        delete_ejecutar.setBackground(new java.awt.Color(0, 0, 0));
        delete_ejecutar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        delete_ejecutar.setForeground(new java.awt.Color(255, 255, 255));
        delete_ejecutar.setText("Eliminar");
        delete_ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_ejecutarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("C R U D");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comprobar_error)
                                .addGap(244, 244, 244))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(create_f)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(delete_ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(36, 36, 36))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 15, Short.MAX_VALUE)
                                                .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                .addGap(91, 91, 91)
                                                .addComponent(jLabel2)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addGap(12, 12, 12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(create_t)
                                            .addComponent(create_d)
                                            .addComponent(create_c))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(create_tr, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(create_cr, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(create_dr, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(create_fr, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(create_ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comprobar, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                            .addComponent(update_ejecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(48, 48, 48))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(create_wrong)
                                .addGap(279, 279, 279))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(create_right)
                                .addGap(226, 226, 226)))))
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(read, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(create_cr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(create_c)
                            .addComponent(comprobar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(create_f)
                            .addComponent(create_fr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete_ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addComponent(comprobar_error)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(create_d)
                            .addComponent(create_dr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(update_ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(create_t)
                            .addComponent(create_tr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(create_ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(create_wrong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(create_right)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readActionPerformed
        // TODO add your handling code here:
        create_c.setVisible(true);
        create_cr.setVisible(true);
        comprobar.setVisible(true);
        
        create_cr.setText("");
        create_fr.setText("");
        create_dr.setText("");
        create_tr.setText("");
        
        create_ejecutar.setVisible(false);
        
        create_f.setVisible(false);
        create_d.setVisible(false);
        create_t.setVisible(false);
        
        create_fr.setVisible(false);
        create_dr.setVisible(false);
        create_tr.setVisible(false);
        
    }//GEN-LAST:event_readActionPerformed

    private void create_crActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_crActionPerformed
        // TODO add your handling code here:8 
        
    }//GEN-LAST:event_create_crActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        
        create_c.setVisible(true);
        create_f.setVisible(true);
        create_d.setVisible(true);
        create_t.setVisible(true);
        
        create_cr.setVisible(true);
        create_fr.setVisible(true);
        create_dr.setVisible(true);
        create_tr.setVisible(true);
        delete_ejecutar.setVisible(false);
        
        // Borrar datos
        create_cr.setText("");
        create_fr.setText("");
        create_dr.setText("");
        create_tr.setText("");
        
        create_ejecutar.setVisible(true);
    }//GEN-LAST:event_createActionPerformed

    private void create_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_ejecutarActionPerformed
        // TODO add your handling code here:
        Factura nuevaFactura = new Factura();
        
        nuevaFactura.setCodigo(Integer.parseInt(create_cr.getText()));
                
        // Array para recoger la fecha
        String[] tokens;
        
        tokens = create_fr.getText().split("-"); // Dividimos los datos y lo almacenamos en el array

        
        int anio = Integer.parseInt(tokens[0]);
        int month = Integer.parseInt(tokens[1]);
        int day = Integer.parseInt(tokens[2]);
        
        // Creamos una nueva instancia de tipo DATE para almacenar los datos de la fecha
        Date fecha = new Date(anio, month, day);
        
        nuevaFactura.setFechaEmision(fecha);
        
        nuevaFactura.setDescripcion(create_dr.getText());
        
        // Creamo una instancia para almacenar el dato después de parsearlo
        BigDecimal total =  new BigDecimal(Double.parseDouble(create_tr.getText()));
        
        nuevaFactura.setTotalImporteFactura(total);
        
        // Creamos una nueva instancia de la Factura JPA
        FacturaJpaController facturaJPA = new FacturaJpaController();
        
        try {
            facturaJPA.create(nuevaFactura);
            create_right.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            create_wrong.setVisible(true);
        }
        
    }//GEN-LAST:event_create_ejecutarActionPerformed

    private void comprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprobarActionPerformed
        // TODO add your handling code here:
        // Creamos una nueva instancia de la Factura JPA
        FacturaJpaController facturaJPA = new FacturaJpaController();
        
        Factura encontrarFact = new Factura();
        
        encontrarFact = facturaJPA.findFactura(Integer.parseInt(create_cr.getText()));
        
        if(encontrarFact != null){
            comprobar.setVisible(false);
            
            create_f.setVisible(true);
            create_d.setVisible(true);
            create_t.setVisible(true);

            create_fr.setVisible(true);
            create_dr.setVisible(true);
            create_tr.setVisible(true);
            
            create_fr.setText(encontrarFact.getFechaEmision().toString());
            create_dr.setText(encontrarFact.getDescripcion().toString());
            create_tr.setText(encontrarFact.getTotalImporteFactura().toString());
            
        }else{
            comprobar_error.setVisible(true);
        }
        
    }//GEN-LAST:event_comprobarActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        create_c.setVisible(true);
        create_cr.setVisible(true);
        comprobar.setVisible(true);  
        update_ejecutar.setVisible(true);
        comprobar_error.setVisible(false);
                
        // Ejecutamos el método para recibir todo 
        comprobarActionPerformed(evt);       
    }//GEN-LAST:event_updateActionPerformed

    private void update_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_ejecutarActionPerformed
        // TODO add your handling code here:
        
        FacturaJpaController facturaJPA = new FacturaJpaController();
        
        Factura actualizarFact = new Factura();
        
        try {
            
            actualizarFact.setCodigo(Integer.parseInt(create_cr.getText()));
                
            // Array para recoger la fecha
            String[] tokens;

            tokens = create_fr.getText().split("-"); // Dividimos los datos y lo almacenamos en el array


            int anio = Integer.parseInt(tokens[0]);
            int month = Integer.parseInt(tokens[1]);
            int day = Integer.parseInt(tokens[2]);

            // Creamos una nueva instancia de tipo DATE para almacenar los datos de la fecha
            Date fecha = new Date(anio, month, day);

            actualizarFact.setFechaEmision(fecha);

            actualizarFact.setDescripcion(create_dr.getText());

            // Creamo una instancia para almacenar el dato después de parsearlo
            BigDecimal total =  new BigDecimal(Double.parseDouble(create_tr.getText()));

            actualizarFact.setTotalImporteFactura(total);
            
            // Realizar update usando el método edit
            facturaJPA.edit(actualizarFact);
            create_right.setVisible(true); // Se ejecuta si la actualización sale correcta
            
        } catch (Exception ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
            create_wrong.setVisible(true);
        }
        
    }//GEN-LAST:event_update_ejecutarActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        create_c.setVisible(true);
        create_cr.setVisible(true);
        delete_ejecutar.setVisible(true); 
        
        create_f.setVisible(false);
        create_d.setVisible(false);
        create_t.setVisible(false);
        
        create_fr.setVisible(false);
        create_dr.setVisible(false);
        create_tr.setVisible(false);
        
        create_right.setVisible(false);
        create_wrong.setVisible(false);
        
        create_ejecutar.setVisible(false);
        comprobar.setVisible(false);
        comprobar_error.setVisible(false);
        update_ejecutar.setVisible(false);
        
    }//GEN-LAST:event_deleteActionPerformed

    private void delete_ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_ejecutarActionPerformed
        // TODO add your handling code here:
        FacturaJpaController facturaJPA = new FacturaJpaController();
        
        int codigo = Integer.parseInt(create_cr.getText());
        
        try {
            facturaJPA.destroy(codigo);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_ejecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton comprobar;
    private javax.swing.JLabel comprobar_error;
    private javax.swing.JButton create;
    private javax.swing.JLabel create_c;
    private javax.swing.JTextField create_cr;
    private javax.swing.JLabel create_d;
    private javax.swing.JTextField create_dr;
    private javax.swing.JButton create_ejecutar;
    private javax.swing.JLabel create_f;
    private javax.swing.JTextField create_fr;
    private javax.swing.JLabel create_right;
    private javax.swing.JLabel create_t;
    private javax.swing.JTextField create_tr;
    private javax.swing.JLabel create_wrong;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete_ejecutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton read;
    private javax.swing.JButton update;
    private javax.swing.JButton update_ejecutar;
    // End of variables declaration//GEN-END:variables
}
